# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20180925_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('allow', 'ALLOW'), ('disallow', 'DISALLOW')], default='new', max_length=9)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.OrganisationItem')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
