# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20180925_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationItem',
            new_name='Organisation',
        ),
    ]
