# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0002_organisation_owners'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organisationtranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='organisationtranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='owners',
        ),
        migrations.AddField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrganisationTranslation',
        ),
    ]
