# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20180925_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='OrganisationBase',
        ),
    ]
