# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20180925_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationbase',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='organisationbase',
            name='owner',
        ),
        migrations.AddField(
            model_name='organisationbase',
            name='title',
            field=models.CharField(help_text='Enter title documentation', max_length=200, null=True),
        ),
    ]
